version: "3.3"

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_raffle
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: raffle_picker
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - rafflenet

  nodeapp:
    container_name: nodeapp
    build: .
    image: nodeapp:v1
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeapp
      PORT: 3000
      MYSQL_HOST: 'mysqldb'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
      MYSQL_DB: 'raffle_picker'
      MYSQL_CONN_LIMIT: '20'
      CLIENT_ID: '355402033198-7nu6fn5qv2a6p6pcgv33chcpll8qlkdk.apps.googleusercontent.com'
    depends_on:
      - mysqldb
    networks:
      - rafflenet

networks:
  rafflenet:
    driver: bridge

